---
apiVersion: apps/v1       # Use stable API version
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx           # Label for selector and Service binding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nag307/project2:latest
          # Expose port 80
          ports:
          - containerPort: 80
          
